//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YwRtdAp.Db.DbObject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RtdBaseContext : DbContext
    {
        public RtdBaseContext()
            : base("name=RtdBaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BizGroup> BizGroup { get; set; }
        public virtual DbSet<Concept> Concept { get; set; }
        public virtual DbSet<Industry> Industry { get; set; }
        public virtual DbSet<PointerIndex> PointerIndex { get; set; }
        public virtual DbSet<Symbol> Symbol { get; set; }
        public virtual DbSet<BizGroupSymbol> BizGroupSymbol { get; set; }
        public virtual DbSet<ConceptSymbol> ConceptSymbol { get; set; }
        public virtual DbSet<IndustrySymbol> IndustrySymbol { get; set; }
        public virtual DbSet<PointerIndexSymbol> PointerIndexSymbol { get; set; }
    }
}
